# This is a basic workflow to help you get started with Actions

name: Build, test and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: appleboy/ssh-action@v0.1.2 #actions/checkout@v2DigiLend/
        with: 
          host: ${{secrets.SSH_HOST}} # IP of server
          key: ${{secrets.SSH_KEY}} # Private or Public key of server
          username: ${{secrets.SSH_USERNAME}} # user of server
          script: |
               fuser -k 9011/tcp # shut down application
               cd DigiLend/Backend
               mvn package # build the application
               cd target
               java -jar digiLend-0.0.1-SNAPSHOT.jar # start the application
               exit


